model_params:
  name: 'CategoricalVAE'
  in_channels: 3
  latent_dim: 512
  categorical_dim: 40
  temperature: 0.5
  anneal_rate: 0.00003
  anneal_interval: 100
  alpha: 1.0

exp_params:
  dataset: 'oxford_robotcar'
  data_path: 'data'
  num_workers_dataloader: 2
  img_size: [64, 64]
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  # scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 10000
  precision: 16

logging_params:
  save_dir: 'logs'
  name: 'CategoricalVAE'
  manual_seed: 1265
