model_params:
  name: 'DIPVAE'
  in_channels: 3
  latent_dim: 64
  lambda_diag: 0.05
  lambda_offdiag: 0.1
  hidden_dims: [32, 64, 128, 256, 512, 1024]

exp_params:
  dataset: 'oxford_robotcar'
  data_path: 'data'
  num_workers_dataloader: 8
  img_size: [128, 128]
  batch_size: 144 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  # scheduler_gamma: 0.97

trainer_params:
  gpus: 1
  max_epochs: 1000
  precision: 16

logging_params:
  save_dir: 'logs'
  name: 'DIPVAE'
  manual_seed: 1265
