model_params:
  name: 'MSSIMVAE'
  in_channels: 3
  latent_dim: 128

exp_params:
  dataset: 'oxford_robotcar'
  data_path: 'data'
  num_workers_dataloader: 2
  img_size: [64, 64]
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  # scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 30
  max_epochs: 10000
  precision: 16

logging_params:
  save_dir: 'logs'
  name: 'MSSIMVAE'
  manual_seed: 1265
